# Generated by Django 4.2.7 on 2024-01-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
