# Generated by Django 4.2.7 on 2024-01-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charo', '0003_alter_commande_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='nbre_jours',
            field=models.PositiveIntegerField(),
        ),
    ]
