# Generated by Django 4.2.7 on 2024-01-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charo', '0004_alter_commande_nbre_jours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='produit',
            new_name='article',
        ),
    ]
